# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

try:
    from . import reflex_pb2 as reflex__pb2
except (ImportError, ValueError):
    import reflex_pb2 as reflex__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in reflex_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ReflexServiceStub(object):
    """ReflexService exposes the Reflex decision engine over gRPC for polyglot
    agent stacks (TypeScript, Go, Rust, etc.).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Decide = channel.unary_unary(
                '/reflex.v1.ReflexService/Decide',
                request_serializer=reflex__pb2.DecideRequest.SerializeToString,
                response_deserializer=reflex__pb2.DecideResponse.FromString,
                _registered_method=True)
        self.Guard = channel.unary_unary(
                '/reflex.v1.ReflexService/Guard',
                request_serializer=reflex__pb2.GuardRequest.SerializeToString,
                response_deserializer=reflex__pb2.GuardResponse.FromString,
                _registered_method=True)
        self.VerifyReceipt = channel.unary_unary(
                '/reflex.v1.ReflexService/VerifyReceipt',
                request_serializer=reflex__pb2.VerifyReceiptRequest.SerializeToString,
                response_deserializer=reflex__pb2.VerifyReceiptResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/reflex.v1.ReflexService/HealthCheck',
                request_serializer=reflex__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=reflex__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class ReflexServiceServicer(object):
    """ReflexService exposes the Reflex decision engine over gRPC for polyglot
    agent stacks (TypeScript, Go, Rust, etc.).
    """

    def Decide(self, request, context):
        """Evaluate a prompt against a typed decision schema.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Guard(self, request, context):
        """Run a prompt through the fail-closed guard reference monitor.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyReceipt(self, request, context):
        """Cryptographically verify a previously emitted decision receipt.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Lightweight liveness / readiness probe.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReflexServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Decide': grpc.unary_unary_rpc_method_handler(
                    servicer.Decide,
                    request_deserializer=reflex__pb2.DecideRequest.FromString,
                    response_serializer=reflex__pb2.DecideResponse.SerializeToString,
            ),
            'Guard': grpc.unary_unary_rpc_method_handler(
                    servicer.Guard,
                    request_deserializer=reflex__pb2.GuardRequest.FromString,
                    response_serializer=reflex__pb2.GuardResponse.SerializeToString,
            ),
            'VerifyReceipt': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyReceipt,
                    request_deserializer=reflex__pb2.VerifyReceiptRequest.FromString,
                    response_serializer=reflex__pb2.VerifyReceiptResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=reflex__pb2.HealthCheckRequest.FromString,
                    response_serializer=reflex__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'reflex.v1.ReflexService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('reflex.v1.ReflexService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ReflexService(object):
    """ReflexService exposes the Reflex decision engine over gRPC for polyglot
    agent stacks (TypeScript, Go, Rust, etc.).
    """

    @staticmethod
    def Decide(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/reflex.v1.ReflexService/Decide',
            reflex__pb2.DecideRequest.SerializeToString,
            reflex__pb2.DecideResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Guard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/reflex.v1.ReflexService/Guard',
            reflex__pb2.GuardRequest.SerializeToString,
            reflex__pb2.GuardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyReceipt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/reflex.v1.ReflexService/VerifyReceipt',
            reflex__pb2.VerifyReceiptRequest.SerializeToString,
            reflex__pb2.VerifyReceiptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/reflex.v1.ReflexService/HealthCheck',
            reflex__pb2.HealthCheckRequest.SerializeToString,
            reflex__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
