"""System 1 Compatibility Modules."""
from system1.compat import typesafe
from system1.compat.typesafe import (
    AsyncClient,
    AsyncTypeSafeClient,
    Choice,
    ChoiceAnswer,
    Client,
    DotDict,
    MultiChoice,
    MultiChoiceAnswer,
    Noul,
    NoulAnswer,
    Score,
    ScoreAnswer,
    SystemOneResponse,
    TypeSafeClient,
    TypeSafeResponse,
    Usage,
    batch_system_one,
    batch_systemone,
    patch_typesafe,
    system_one,
    systemone,
    call_real_typesafe_api,
    create_typesafe_baseline_response,
    compare,
)

__all__ = [
    "typesafe",
    "TypeSafeClient",
    "Client",
    "AsyncTypeSafeClient",
    "AsyncClient",
    "Choice",
    "MultiChoice",
    "Noul",
    "Score",
    "TypeSafeResponse",
    "SystemOneResponse",
    "ChoiceAnswer",
    "NoulAnswer",
    "ScoreAnswer",
    "MultiChoiceAnswer",
    "Usage",
    "system_one",
    "systemone",
    "batch_system_one",
    "batch_systemone",
    "patch_typesafe",
    "DotDict",
    "call_real_typesafe_api",
    "create_typesafe_baseline_response",
    "compare",
]

